In [1]:
from IPython.display import Image
from IPython.display import HTML
import matplotlib.pyplot as plt
import numpy as np
import numpy.random as npr
import math
import random


#<font size="+3"> Usando o numpy  </font>

In [2]:
#percMelhor = np
numIterations = 1000
numExec = 5

percMelhor = np.zeros((numExec, numIterations ))
print(percMelhor)

print('\nComeça as 5 execuções.\n')


#Execução 0

print('Execução 0')
print('Iteração 0')

percMelhor[0 , 0] = 70

print(percMelhor)

print('Execução 0')
print('Iteração 1')

percMelhor[0 , 1] = 73

print('O processo continua até a última iteração')

print(percMelhor)


#Execução 1


print('Execução 1')
print('Iteração 0')

percMelhor[1 , 0] = 60

print(percMelhor)

print('Execução 1')
print('Iteração 1')

percMelhor[1 , 1] = 80

print('O processo continua até a última iteração')

print(percMelhor)

print('e assim por diante para as outras execuções')

#Para cada iteração calcular a média

#Calcular a média da melhor sequência por execução para cada iteração
meanMelhor = np.zeros(( numIterations ))
for iteration in np.arange(0, np.shape(percMelhor)[ 1 ]):
    meanMelhor[ iteration ] = np.mean( percMelhor[ :, iteration ] )
    
#Plot meanMelhor

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Começa as 5 execuções.

Execução 0
Iteração 0
[[70.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
Execução 0
Iteração 1
O processo continua até a última iteração
[[70. 73.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
Execução 1
Iteração 0
[[70. 73.  0. ...  0.  0.  0.]
 [60.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
Execução 1
Iteração 1
O processo continua até a última iteração
[[70. 73.  0. ...  0.  0.  0.]
 [60. 80.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
e assim por diante para as outras execuções


In [21]:
import random
#percMelhor = np
numIterations = 10
numExec = 5

percMelhor = np.zeros((numExec, numIterations ))
print(percMelhor)

print('\nComeça as 5 execuções.\n')


iteracoes = 0

liste = random.sample(range(-100,100), 10)


def sequencias(execs, iteracoes,liste):
        execucao = list(range(10))
        while iteracoes <=10:
            for n in execucao:
                print('Execução ' , n)
                print('Iteração ' , iteracoes)

                percMelhor[0 , n] = liste[n]

                print(percMelhor)

                iteracoes = iteracoes + 1
                print(n)
            
            
            
            
sequencias(5, 0, liste)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Começa as 5 execuções.

Execução  0
Iteração  0
[[-32.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
0
Execução  1
Iteração  1
[[-32. -20.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
1
Execução  2
Iteração  2
[[-32. -20.  42.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 

In [22]:
#percMelhor = np
numIterations = 6
numExec = 5

percMelhor = np.zeros((numExec, numIterations ))
print(percMelhor)

print('\nComeça as 5 execuções.\n')

execucao = list(range(100))

def sequencias(execucao, iteracoes):
       for n in execucao:
            print(n)
            
sequencias(execucao, 6).

SyntaxError: invalid syntax (<ipython-input-22-a483cda0d76f>, line 16)

In [52]:
execucao = list(range(10))
iteracao = list(range(10))

def sequencias(execucao, iteracoes):
       for n in execucao:
            
            for m in iteracao:
                print("n",n)
                print("m",m)
            
sequencias(execucao, iteracao).

SyntaxError: invalid syntax (<ipython-input-52-b357f2c76def>, line 11)

In [183]:
vet = [1,2,3,4,5,6,7,8,9,10]

vet = vet[4:6]

print(vet)
print(vet2)

[5, 6]
[2, 3]


In [ ]:
3x,2x,4x

In [ ]:
vetor = []

def sequencias(c1,c2,c3,vetor):
    i = 0
    while i<50:
        lista = random.sample(range(-10,10), 3)
        
        i = i +1
        print(lista)
        s1 = 3*lista[0] + 2*lista[1] + 4*lista[2]
        s2 = lista[0] + lista[1] + 2*lista[2]
        s3 = 4*lista[0] + 3*lista[1] - 2*lista[2]
        
        a1 = abs((c1-s1)/c1)*100
        a2 = abs((c2-s2)/c2)*100
        a3 = abs((c3-s3)/c3)*100
        
        media = ((a1+a2+a3)/3)
        
        vetor.append(media)
        vetor.sort()
        vetor = vetor[0:24]
        
    
    while(len(vetor))<1000:
        while i<2*(len(vetor)):
        
            lista = random.sample(range(-10,10), 3)
            s1 = 3*lista[0] + 2*lista[1] + 4*lista[2]
            s2 = lista[0] + lista[1] + 2*lista[2]
            s3 = 4*lista[0] + 3*lista[1] - 2*lista[2]

            a1 = abs((c1-s1)/c1)*100
            a2 = abs((c2-s2)/c2)*100
            a3 = abs((c3-s3)/c3)*100

            media = ((a1+a2+a3)/3)

            vetor.append(media)
            vetor.sort()
            vetor = vetor[0:24]
            print(len(vetor))
      
i = 0
sequencias(1,2,3,vetor)